# version: '3.8'

services:
  nginx:
    image: nginx:alpine
    platform: linux/amd64
    container_name: alpha-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    environment:
      - LETSENCRYPT_DOMAIN=${LETSENCRYPT_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - php
    networks:
      - alpha-network

  php:
    build:
      context: .
      platforms: 
        - linux/amd64
      dockerfile: ./bin/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
    container_name: alpha-php
    platform: linux/amd64
    volumes:
      - ./www:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - alpha-network

  mysql:
    image: mysql:${MYSQL_VERSION}
    platform: linux/amd64
    container_name: alpha-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - alpha-network
    deploy:
      replicas: 1
    restart: "no"

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: alpha-postgres
    platform: linux/amd64
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - alpha-network
    deploy:
      replicas: 1
    restart: "no"

  redis:
    image: redis:alpine
    container_name: alpha-redis
    platform: linux/amd64
    ports:
      - "6379:6379"
    networks:
      - alpha-network

  certbot:
    image: certbot/certbot
    # platform: linux/amd64
    container_name: alpha-certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    environment:
      - CERTBOT_DOMAIN=${LETSENCRYPT_DOMAIN}
      - CERTBOT_EMAIL=${LETSENCRYPT_EMAIL}
    entrypoint: "/bin/sh -c 'if [ \"$ENABLE_HTTPS\" = \"true\" ]; then trap exit TERM; while :; do certbot certonly --webroot -w /var/www/certbot -d $CERTBOT_DOMAIN --email $CERTBOT_EMAIL --agree-tos; sleep 12h & wait $${!}; done; else sleep infinity; fi;'"
    networks:
      - alpha-network

networks:
  alpha-network:
    name: alpha-network